export const FP_MESSAGE = {
    LOGIN_SUCCESSFUL: 'Login Successful!',
    LOGIN_TO_CONTINUE: 'Please log in to continue.',
    LOGIN_FAILED: 'Login failed. Please check your email and password.',
    LOGOUT_SUCCESSFUL: 'Logout Successful!',
    UNAUTHORIZED: 'Unauthorized access. Please log in again.',
    FORBIDDEN: 'You do not have permission to access this content.',
    INTERNAL_SERVER_ERROR: 'Oops! Theres been an issue with your request. Please try again later.',
    REGISTRATION_SUCCESSFUL: 'Registration Successful!',
    REGISTRATION_FAILED: 'Error during registration. Please try again.',
    PASSWORD_CHANGE_SUCCESSFUL: 'Password changed successfully!',
    PASSWORD_CHANGE_FAILED: 'Error changing password. Please try again.',
    PASSWORD_FORGET_SUCCESSFUL: 'Recovery email sent. Please check your email.',
    PASSWORD_FORGET_FAILED: 'Unable to send recovery email at the moment. Please try again later.',
    PAGE_UNDER_MAINTENANCE: 'Page under maintenance. Please check back later.',
    VALIDATION_FAILED: 'Validation failed. Please review your input.',

    CART_ADD_SUCCESSFUL: 'Product added to cart!',
    CART_ADD_FAILED: 'Error adding product to cart. Please try again.',
    CART_REMOVE_SUCCESSFUL: 'Product removed from cart!',
    CART_REMOVE_FAILED: 'Error removing product from cart. Please try again.',
    CART_FETCH_SUCCESSFUL: 'Cart fetched successfully!',

    CHECKOUT_SUCCESSFUL: 'Checkout successful!',
    CHECKOUT_FAILED: 'Error during checkout. Please try again.',

    ORDER_FETCH_SUCCESSFUL: 'Order fetched successfully!',
    ORDER_FETCH_FAILED: 'Error fetching order. Please try again.',
    ORDER_CANCEL_SUCCESSFUL: 'Order cancelled successfully!',
    ORDER_CANCEL_FAILED: 'Error cancelling order. Please try again.',
    ORDER_DELETE_SUCCESSFUL: 'Order deleted successfully!',
    ORDER_DELETE_FAILED: 'Error deleting order. Please try again.',
    ORDER_UPDATE_SUCCESSFUL: 'Order updated successfully!',
    ORDER_UPDATE_FAILED: 'Error updating order. Please try again!',

    FETCH_FAILED: 'Error fetching data. Please try again.',
    FETCH_SUCCESSFUL: 'Data fetched successfully!',
}

export const FP_CMS_MESSAGES = {
    CMS_ADD_PRODUCT_SUCCESSFUL: 'Product added successfully!',
    CMS_ADD_PRODUCT_FAILED: 'Error adding product. Please try again.',
    CMS_UPDATE_PRODUCT_SUCCESSFUL: 'Product updated successfully!',
    CMS_UPDATE_PRODUCT_FAILED: 'Error updating product. Please try again.',
    CMS_DELETE_PRODUCT_SUCCESSFUL: 'Product deleted successfully!',
    CMS_DELETE_PRODUCT_FAILED: 'Error deleting product. Please try again.',
    CMS_ADD_CATEGORY_SUCCESSFUL: 'Category added successfully!',
    CMS_ADD_CATEGORY_FAILED: 'Error adding category. Please try again.',
    CMS_UPDATE_CATEGORY_SUCCESSFUL: 'Category updated successfully!',
    CMS_UPDATE_CATEGORY_FAILED: 'Error updating category. Please try again.',
    CMS_DELETE_CATEGORY_SUCCESSFUL: 'Category deleted successfully!',
    CMS_DELETE_CATEGORY_FAILED: 'Error deleting category. Please try again.',
    
    CMS_ADD_BRAND_SUCCESSFUL: 'Brand added successfully!',
    CMS_ADD_BRAND_FAILED: 'Error adding brand. Please try again.',
    CMS_UPDATE_BRAND_SUCCESSFUL: 'Brand updated successfully!',
    CMS_UPDATE_BRAND_FAILED: 'Error updating brand. Please try again.',
    CMS_DELETE_BRAND_SUCCESSFUL: 'Brand deleted successfully!',
    CMS_DELETE_BRAND_FAILED: 'Error deleting brand. Please try again.',

    CMS_CONFIRM_ORDER_SUCCESSFUL: 'Order confirmed successfully!',
    CMS_CONFIRM_ORDER_FAILED: 'Error confirming order. Please try again.',
    CMS_CANCEL_ORDER_SUCCESSFUL: 'Order cancelled successfully!',
    CMS_CANCEL_ORDER_FAILED: 'Error cancelling order. Please try again.',
    CMS_DELETE_ORDER_SUCCESSFUL: 'Order deleted successfully!',
    CMS_DELETE_ORDER_FAILED: 'Error deleting order. Please try again.',
    CMS_UPDATE_ORDER_SUCCESSFUL: 'Order updated successfully!',
    CMS_UPDATE_ORDER_FAILED: 'Error updating order. Please try again.',

    CMS_ADD_USER_SUCCESSFUL: 'User added successfully!',
    CMS_ADD_USER_FAILED: 'Error adding user. Please try again.',
    CMS_UPDATE_USER_SUCCESSFUL: 'User updated successfully!',
    CMS_UPDATE_USER_FAILED: 'Error updating user. Please try again.',
    CMS_DELETE_USER_SUCCESSFUL: 'User deleted successfully!',
    CMS_DELETE_USER_FAILED: 'Error deleting user. Please try again.',
    CMS_ADD_USER_ROLE_SUCCESSFUL: 'User role added successfully!',
    CMS_ADD_USER_ROLE_FAILED: 'Error adding user role. Please try again.',
}
